In [1]:
import pandas as pd

In [6]:
df = pd.read_csv('/Users/tracylee/raw_dogs/clean_without_dummies_5_nodead.csv')

In [11]:
df.columns

Index([u'Unnamed: 0', u'animalActivityLevel', u'animalAdoptionFee',
       u'animalAltered', u'animalBiggestPictures', u'animalBiggestVideos',
       u'animalBreed', u'animalColor', u'animalDeclawed',
       u'animalDescriptionPlain', u'animalGeneralAge',
       u'animalGeneralSizePotential', u'animalHousetrained',
       u'animalIndoorOutdoor', u'animalLocationState', u'animalMicrochipped',
       u'animalMixedBreed', u'animalNeedsFoster', u'animalNewPeople',
       u'animalNumPictures', u'animalNumVideos', u'animalOKWithCats',
       u'animalOKWithDogs', u'animalOKWithKids', u'animalOrgID',
       u'animalPrimaryBreed', u'animalSearchString', u'animalSecondaryBreed',
       u'animalSex', u'animalSizeCurrent', u'animalSizePotential',
       u'animalSpecialneeds', u'animalUptodate', u'start_date', u'end_date',
       u'adopted', u'censored', u'time_range', u'age_at_start', u'has_url',
       u'in_foster', u'mostly_black', u'region', u'search_string_num_terms',
       u'description_length'],
      dtype='object')

In [9]:
def state_to_region(x):
    West = ['CA','UT','WY','MT', 'OR','WA',
            'CO','AZ','NM','NV', 'AK', 'ID']
    Midwest = ['IL','MI','IN','MO', 'MN','KS',
              'OH','ND','WI', 'IA', 'SD','NE']
    South = ['TX','NC','MD', 'WV', 'KY', 'TN',
            'DE', 'OK','FL','LA', 'VA','SC',
            'GA', 'AL','AR','MS','DC']
    Northeast = ['PA','VT','NY','MA','NJ', 'RI',
                'ME','CT','NH']
    Canada = ['NS', 'ON', 'QC','AB','BC']
    Territory = ['VI','PR']

    region_names = ['West', 'Midwest', 'South', 'Northeast', 'Canada', 'Territory']
    regions = [West, Midwest, South, Northeast, Canada, Territory]
    for i, region in enumerate(regions):
        if x in region:
            return region_names[i]

def breed_groups(df):
    df['pitbull']=df[u'animalBreed'].apply(lambda x: 1 if 'pit bull' in x.lower()
                                                   else 1 if 'bull terrier' in x.lower()
                                                   else 1 if 'staffordshire' in x.lower()
                                                   else 1 if 'american bulldog' in x.lower()
                                                   else 1 if 'bully' in x.lower()
                                                   else 0)
    df['Terrier']=df[u'animalBreed'].apply(lambda x: 1 if 'terrier' in x.lower()
                                                   else 0)
    df['Hound']=df[u'animalBreed'].apply(lambda x: 1 if 'hound' in x.lower()
                                                     else 1 if 'hund' in x.lower()
                                                       else 0)
    df['Herding']=df[u'animalBreed'].apply(lambda x: 1 if 'herd' in x.lower()
                                                     else 1 if 'shep' in x.lower()
                                                    else 1 if 'sheep' in x.lower()
                                                       else 1 if 'corgi' in x.lower()
                                                       else 1 if 'collie' in x.lower()
                                                       else 0)
    df['Working']=df[u'animalBreed'].apply(lambda x: 1 if 'retriever' in x.lower()
                                                     else 1 if 'setter' in x.lower()
                                                    else 1 if 'spaniel' in x.lower()
                                                       else 1 if 'pointer' in x.lower()
                                                       else 0)
    return df

In [10]:
df['mostly_black'] = df['animalColor'].apply(lambda x: 1 if str(x)[:5]=='Black' else 0)
df['region'] = df['animalLocationState'].apply(lambda x: state_to_region(x))
df['search_string_num_terms'] = df['animalSearchString'].apply(lambda x: len(str(x).split()))
df['description_length'] = df['animalDescriptionPlain'].apply(lambda x: len(str(x)))

In [20]:
df2 = pd.read_csv('data/clean_data_no_dummies.csv')

In [21]:
df2.columns

Index([u'Unnamed: 0', u'animalActivityLevel', u'animalAdoptionFee',
       u'animalAltered', u'animalBiggestPictures', u'animalBiggestVideos',
       u'animalBreed', u'animalColor', u'animalDeclawed', u'animalGeneralAge',
       u'animalGeneralSizePotential', u'animalHousetrained',
       u'animalIndoorOutdoor', u'animalMicrochipped', u'animalMixedBreed',
       u'animalNeedsFoster', u'animalNewPeople', u'animalNumPictures',
       u'animalNumVideos', u'animalOKWithCats', u'animalOKWithDogs',
       u'animalOKWithKids', u'animalOrgID', u'animalPrimaryBreed',
       u'animalSearchString', u'animalSecondaryBreed', u'animalSex',
       u'animalSizeCurrent', u'animalSizePotential', u'animalSpecialneeds',
       u'animalUptodate', u'start_date', u'end_date', u'adopted', u'censored',
       u'time_range', u'age_at_start', u'has_url', u'in_foster',
       u'mostly_black', u'search_string_num_terms', u'description_length',
       u'has_video', u'desc_latent_topic', u'region', u'Pitbull', u'Terrier',
       u'Hound', u'Herding', u'Working'],
      dtype='object')

In [22]:
df2.shape

(152259, 50)

In [24]:
df[['Desc_Latent_Topic',u'Has_Video',u'Pitbull', u'Terrier',
       u'Hound', u'Herding', u'Working']] = df2[['desc_latent_topic',u'has_video',u'Pitbull', u'Terrier',
       u'Hound', u'Herding', u'Working']]

In [33]:
df.columns=[        u'ActivityLevel',
                u'AdoptionFee',              u'Altered',
            u'BiggestPictures',        u'BiggestVideos',
                      u'Breed',                u'Color',
                   u'Declawed',     u'DescriptionPlain',
                 u'GeneralAge', u'GeneralSizePotential',
               u'Housetrained',        u'IndoorOutdoor',
              u'LocationState',         u'Microchipped',
                 u'MixedBreed',          u'NeedsFoster',
                  u'NewPeople',          u'NumPictures',
                  u'NumVideos',           u'OKWithCats',
                 u'OKWithDogs',           u'OKWithKids',
                      u'OrgID',         u'PrimaryBreed',
               u'SearchString',       u'SecondaryBreed',
                        u'Sex',          u'SizeCurrent',
              u'SizePotential',         u'Specialneeds',
                   u'Uptodate',                 u'Start_Date',
                         u'End_Date',                    u'Adopted',
                         u'Censored',                 u'Time',
                     u'Age_at_Start',                    u'Has_url',
                        u'In_Foster',               u'Mostly_Black',
                           u'Region',    u'Search_String_Num_Terms',
               u'Description_Length',          u'Desc_Latent_Topic',
                        u'Has_Video',                    u'Pitbull',
                          u'Terrier',                      u'Hound',
                          u'Herding',                    u'Working']

In [40]:
def fill_na_mean(df, fields):
    for field in fields:
        df[field].fillna(df[field].mean(), inplace=True)
    return df

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152259 entries, 0 to 152258
Data columns (total 51 columns):
ActivityLevel              100425 non-null object
AdoptionFee                59107 non-null float64
Altered                    94550 non-null float64
BiggestPictures            96174 non-null float64
BiggestVideos              96174 non-null float64
Breed                      152259 non-null object
Color                      124753 non-null object
Declawed                   32541 non-null float64
DescriptionPlain           143750 non-null object
GeneralAge                 138897 non-null object
GeneralSizePotential       131268 non-null object
Housetrained               76945 non-null float64
IndoorOutdoor              81539 non-null object
LocationState              152259 non-null object
Microchipped               73922 non-null float64
MixedBreed                 110778 non-null float64
NeedsFoster                142862 non-null float64
NewPeople                  61941 non-null object
NumPictures                152259 non-null float64
NumVideos                  152259 non-null float64
OKWithCats                 66373 non-null float64
OKWithDogs                 119700 non-null float64
OKWithKids                 95241 non-null float64
OrgID                      152259 non-null float64
PrimaryBreed               152259 non-null object
SearchString               152259 non-null object
SecondaryBreed             55011 non-null object
Sex                        150596 non-null object
SizeCurrent                136372 non-null float64
SizePotential              121449 non-null float64
Specialneeds               119966 non-null float64
Uptodate                   114623 non-null float64
Start_Date                 152259 non-null object
End_Date                   152259 non-null object
Adopted                    152259 non-null int64
Censored                   152259 non-null int64
Time                       152259 non-null int64
Age_at_Start               128743 non-null float64
Has_url                    152259 non-null int64
In_Foster                  152259 non-null int64
Mostly_Black               152259 non-null int64
Region                     152259 non-null object
Search_String_Num_Terms    152259 non-null int64
Description_Length         152259 non-null int64
Desc_Latent_Topic          152259 non-null object
Has_Video                  152259 non-null int64
Pitbull                    152259 non-null int64
Terrier                    152259 non-null int64
Hound                      152259 non-null int64
Herding                    152259 non-null int64
Working                    152259 non-null int64
dtypes: float64(20), int64(14), object(17)
memory usage: 59.2+ MB

In [45]:
import re
def adoption_fee_parse(x):
    if pd.isnull(x):
        return np.nan
    else:
        regex = re.findall(r'\d+', x)
        if len(regex)>0:
            return sum([float(num) for num in regex])
        else:
            return np.nan
        
df['AdoptionFee'] = df['AdoptionFee'].apply(lambda x: adoption_fee_parse(x))

In [47]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152259 entries, 0 to 152258
Data columns (total 50 columns):
Unnamed: 0                    152259 non-null int64
animalActivityLevel           152259 non-null object
animalAdoptionFee             152259 non-null float64
animalAltered                 152259 non-null float64
animalBiggestPictures         152259 non-null float64
animalBiggestVideos           152259 non-null float64
animalBreed                   152259 non-null object
animalColor                   152259 non-null object
animalDeclawed                152259 non-null float64
animalGeneralAge              152259 non-null object
animalGeneralSizePotential    152259 non-null object
animalHousetrained            152259 non-null object
animalIndoorOutdoor           152259 non-null object
animalMicrochipped            152259 non-null object
animalMixedBreed              152259 non-null float64
animalNeedsFoster             152259 non-null float64
animalNewPeople               152259 non-null object
animalNumPictures             152259 non-null float64
animalNumVideos               152259 non-null float64
animalOKWithCats              152259 non-null object
animalOKWithDogs              152259 non-null object
animalOKWithKids              152259 non-null object
animalOrgID                   152259 non-null float64
animalPrimaryBreed            152259 non-null object
animalSearchString            152259 non-null object
animalSecondaryBreed          152259 non-null object
animalSex                     152259 non-null object
animalSizeCurrent             136372 non-null float64
animalSizePotential           121449 non-null float64
animalSpecialneeds            152259 non-null float64
animalUptodate                152259 non-null float64
start_date                    152259 non-null object
end_date                      152259 non-null object
adopted                       152259 non-null int64
censored                      152259 non-null int64
time_range                    152259 non-null int64
age_at_start                  128743 non-null float64
has_url                       152259 non-null int64
in_foster                     152259 non-null int64
mostly_black                  152259 non-null int64
search_string_num_terms       152259 non-null int64
description_length            152259 non-null int64
has_video                     152259 non-null int64
desc_latent_topic             152259 non-null int64
region                        152259 non-null object
Pitbull                       152259 non-null int64
Terrier                       152259 non-null int64
Hound                         152259 non-null int64
Herding                       152259 non-null int64
Working                       152259 non-null int64
dtypes: float64(15), int64(16), object(19)
memory usage: 58.1+ MB

In [48]:
df.columns

Index([u'ActivityLevel', u'AdoptionFee', u'Altered', u'BiggestPictures',
       u'BiggestVideos', u'Breed', u'Color', u'Declawed', u'DescriptionPlain',
       u'GeneralAge', u'GeneralSizePotential', u'Housetrained',
       u'IndoorOutdoor', u'LocationState', u'Microchipped', u'MixedBreed',
       u'NeedsFoster', u'NewPeople', u'NumPictures', u'NumVideos',
       u'OKWithCats', u'OKWithDogs', u'OKWithKids', u'OrgID', u'PrimaryBreed',
       u'SearchString', u'SecondaryBreed', u'Sex', u'SizeCurrent',
       u'SizePotential', u'Specialneeds', u'Uptodate', u'Start_Date',
       u'End_Date', u'Adopted', u'Censored', u'Time', u'Age_at_Start',
       u'Has_url', u'In_Foster', u'Mostly_Black', u'Region',
       u'Search_String_Num_Terms', u'Description_Length', u'Desc_Latent_Topic',
       u'Has_Video', u'Pitbull', u'Terrier', u'Hound', u'Herding', u'Working'],
      dtype='object')

In [51]:
df[[u'ActivityLevel', u'AdoptionFee', u'Altered', u'BiggestPictures',
       u'BiggestVideos', u'Breed', u'Color', u'Declawed',
       u'GeneralAge', u'GeneralSizePotential', u'Housetrained',
       u'IndoorOutdoor',  u'Microchipped', u'MixedBreed',
       u'NeedsFoster', u'NewPeople', u'NumPictures', u'NumVideos',
       u'OKWithCats', u'OKWithDogs', u'OKWithKids', u'OrgID', u'PrimaryBreed',
       u'SearchString', u'SecondaryBreed', u'Sex', u'SizeCurrent',
       u'SizePotential', u'Specialneeds', u'Uptodate']] = df2[[u'animalActivityLevel', u'animalAdoptionFee',
       u'animalAltered', u'animalBiggestPictures', u'animalBiggestVideos',
       u'animalBreed', u'animalColor', u'animalDeclawed', u'animalGeneralAge',
       u'animalGeneralSizePotential', u'animalHousetrained',
       u'animalIndoorOutdoor', u'animalMicrochipped', u'animalMixedBreed',
       u'animalNeedsFoster', u'animalNewPeople', u'animalNumPictures',
       u'animalNumVideos', u'animalOKWithCats', u'animalOKWithDogs',
       u'animalOKWithKids', u'animalOrgID', u'animalPrimaryBreed',
       u'animalSearchString', u'animalSecondaryBreed', u'animalSex',
       u'animalSizeCurrent', u'animalSizePotential', u'animalSpecialneeds',
       u'animalUptodate']]

In [53]:
df['DescriptionPlain'].fillna('', inplace=True)

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152259 entries, 0 to 152258
Data columns (total 51 columns):
ActivityLevel              152259 non-null object
AdoptionFee                152259 non-null float64
Altered                    152259 non-null float64
BiggestPictures            152259 non-null float64
BiggestVideos              152259 non-null float64
Breed                      152259 non-null object
Color                      152259 non-null object
Declawed                   152259 non-null float64
DescriptionPlain           152259 non-null object
GeneralAge                 152259 non-null object
GeneralSizePotential       152259 non-null object
Housetrained               152259 non-null object
IndoorOutdoor              152259 non-null object
LocationState              152259 non-null object
Microchipped               152259 non-null object
MixedBreed                 152259 non-null float64
NeedsFoster                152259 non-null float64
NewPeople                  152259 non-null object
NumPictures                152259 non-null float64
NumVideos                  152259 non-null float64
OKWithCats                 152259 non-null object
OKWithDogs                 152259 non-null object
OKWithKids                 152259 non-null object
OrgID                      152259 non-null float64
PrimaryBreed               152259 non-null object
SearchString               152259 non-null object
SecondaryBreed             152259 non-null object
Sex                        152259 non-null object
SizeCurrent                136372 non-null float64
SizePotential              121449 non-null float64
Specialneeds               152259 non-null float64
Uptodate                   152259 non-null float64
Start_Date                 152259 non-null object
End_Date                   152259 non-null object
Adopted                    152259 non-null int64
Censored                   152259 non-null int64
Time                       152259 non-null int64
Age_at_Start               128743 non-null float64
Has_url                    152259 non-null int64
In_Foster                  152259 non-null int64
Mostly_Black               152259 non-null int64
Region                     152259 non-null object
Search_String_Num_Terms    152259 non-null int64
Description_Length         152259 non-null int64
Desc_Latent_Topic          152259 non-null object
Has_Video                  152259 non-null int64
Pitbull                    152259 non-null int64
Terrier                    152259 non-null int64
Hound                      152259 non-null int64
Herding                    152259 non-null int64
Working                    152259 non-null int64
dtypes: float64(15), int64(14), object(22)
memory usage: 59.2+ MB

In [55]:

r_df = df.copy()

In [59]:
def group_breeds(row):
    if row['Pitbull']==1:
        return 'Pitbull'
    elif row['Terrier']==1:
        return 'Terrier'
    elif row['Hound']==1:
        return 'Hound' 
    elif row['Herding']==1:
        return 'Herding' 
    elif row['Working']==1:
        return 'Working' 
    else: return 'Other'

In [61]:
r_df['Breed_Group'] = df.apply(lambda row: group_breeds(row),axis=1)

In [65]:
for col in r_df.columns:
    print col, ":", r_df[col].unique()

ActivityLevel : ['Unknown' 'Moderately Active' 'Highly Active' 'Slightly Active'
 'Not Active']
AdoptionFee : [  2.65085320e+02   4.00000000e+02   3.50000000e+02   3.00000000e+02
   1.50000000e+02   2.25000000e+02   2.75000000e+02   2.50000000e+02
   2.00000000e+02   6.00000000e+02   0.00000000e+00   1.00000000e+02
   4.25000000e+02   2.30000000e+02   3.53000000e+02   4.50000000e+02
   1.25000000e+02   3.75000000e+02   5.00000000e+02   9.00000000e+01
   3.25000000e+02   1.75000000e+02   2.20000000e+02   1.30000000e+02
   2.80000000e+02   7.50000000e+01   3.30000000e+02   5.00000000e+01
   2.85000000e+02   2.15000000e+02   2.05000000e+02   4.03000000e+02
   2.50000000e+01   1.53000000e+02   4.50000000e+01   1.35000000e+02
   8.50000000e+01   3.20000000e+02   1.60000000e+02   2.60000000e+02
   1.55000000e+02   2.65000000e+02   2.47000000e+03   9.50000000e+01
   1.65000000e+02   7.00000000e+02   1.70000000e+02   8.60300000e+03
   2.00000000e+01   5.50000000e+02   3.60000000e+02   9.90000000e+01
   5.00000000e+00   2.10000000e+02   3.70000000e+02   6.50000000e+02
   5.75000000e+02   1.00000000e+00   2.00000000e+03   6.50000000e+01
   1.10000000e+02   8.00000000e+01   2.62000000e+02   2.40000000e+02
   1.80000000e+02   1.20000000e+02   4.00000000e+01   1.20000000e+03
   1.95000000e+02   2.45000000e+02   1.85000000e+02   2.35000000e+02
   5.50000000e+01   2.12000000e+02   3.31000000e+02   1.40000000e+02
   7.30000000e+01   2.03000000e+02   4.99000000e+02   3.51000000e+02
   2.00900000e+03   4.78000000e+02   3.00000000e+01   6.84000000e+03
   1.45000000e+02   3.80000000e+02   4.10000000e+02   2.90000000e+02
   3.85000000e+02   2.00000000e+00   3.99000000e+02   1.15000000e+02
   8.00000000e+02   2.95000000e+02   4.75000000e+02   9.40000000e+01
   5.99000000e+02   2.99000000e+02   3.00000000e+00   3.50000000e+01
   1.12000000e+02   3.10000000e+02   9.60000000e+01   1.99000000e+02
   4.12000000e+02   2.37000000e+02   9.20000000e+01   2.89000000e+02
   6.00000000e+01   4.60000000e+02   7.50000000e+02   4.95000000e+02
   4.40000000e+02   6.99000000e+02   1.10000000e+03   3.45000000e+02
   9.00000000e+02   6.70000000e+01   1.27000000e+02   5.10000000e+02
   7.99000000e+02   3.05000000e+02   3.95000000e+02   4.85000000e+02
   1.00000000e+01   4.30000000e+02   5.60000000e+02   5.25000000e+02
   9.99000000e+02   6.30000000e+01   8.30000000e+01   3.70000000e+01
   3.49000000e+02   1.90000000e+02   5.74000000e+02   3.65000000e+02
   3.12000000e+02   1.62000000e+02   1.25000000e+03   1.82000000e+02
   1.37000000e+02   2.76000000e+02   1.87000000e+02   1.05000000e+02
   7.00000000e+01   2.32000000e+02   1.67000000e+02   1.13000000e+02
   3.15000000e+02   2.55000000e+02   7.90000000e+01   2.70000000e+02
   3.35000000e+02   8.75000000e+02   1.33000000e+02   3.72000000e+02
   6.10000000e+02   2.01000000e+02   3.24000000e+02   2.16000000e+02
   1.40000000e+01   8.99000000e+02   4.45000000e+02   1.92000000e+02
   4.70000000e+02   6.90000000e+02   2.29000000e+02   3.48000000e+02
   4.68000000e+02   3.59000000e+02   4.80000000e+02   4.15000000e+03
   5.40000000e+02   1.38000000e+02   2.08000000e+02   2.69000000e+02
   1.72000000e+02   1.88000000e+02   1.89000000e+02   3.90000000e+02
   5.98000000e+02   5.70000000e+02   2.48000000e+02   6.20000000e+02
   2.44000000e+02   1.54000000e+02   4.28000000e+02   1.44000000e+02
   2.39000000e+02   2.86000000e+02   4.77000000e+02   2.79000000e+02
   3.83000000e+02   2.88000000e+02   1.69000000e+02   1.91000000e+02
   7.80000000e+02   4.04000000e+02   4.88000000e+02   5.08000000e+02
   2.87000000e+02   3.40000000e+02   2.49000000e+02   4.21000000e+02
   1.49000000e+02   3.79000000e+02   4.39000000e+02   5.72000000e+02
   5.48000000e+02   4.29000000e+02   3.29000000e+02   1.29000000e+02
   2.11000000e+02   1.09000000e+02   5.56000000e+02   2.58000000e+02]
Altered : [ 1.  0.]
BiggestPictures : [ 96769.  95768.  98461. ...,  69569.  60209.  58816.]
BiggestVideos : [        0.  21789308.   5493770. ...,   4549219.  12333120.   8420079.]
Breed : ['Boxer' 'Labrador Retriever / Boxer / Mixed' 'Poodle (Toy)' ...,
 'French Bulldog / German Shepherd Dog / Mixed (short coat)'
 'German Wirehaired Pointer / Black Labrador Retriever / Mixed (short coat)'
 'Boxer / American Foxhound / Mixed (short coat)']
Color : ['Unknown' 'Black' 'White' 'Black with Tan, Yellow or Fawn'
 'Black with White' 'Red' 'Tan' 'White with Tan, Yellow or Fawn'
 'White with Black' 'Tricolor (Tan/Brown & Black & White)'
 'Gray/Silver/Salt & Pepper with Black' 'Brindle with White'
 'Red/Golden/Orange/Chestnut with White' 'Brown/Chocolate' 'Brindle'
 'Brown/Chocolate with White' 'Golden/Chestnut'
 'Brown/Chocolate with Black' 'Tan/Yellow/Fawn with White'
 'Black with Brown, Red, Golden, Orange or Chestnut'
 'Silver & Tan (Yorkie colors)' 'Tan/Yellow/Fawn with Black' 'Fawn'
 'Yellow' 'White with Red, Golden, Orange or Chestnut' 'Merle'
 'Red/Golden/Orange/Chestnut with Black' 'Gray' 'Black with Gray or Silver'
 'Gray/Silver/Salt & Pepper with White' 'Blue/Silver/Salt & Pepper'
 'Brown/Chocolate with Tan' 'White with Gray or Silver'
 'White with Brown or Chocolate' 'Orange' 'Sable' 'Liver with White'
 'Lemon with White' 'Cream' 'Multi/Mixed' 'Blonde']
Declawed : [ 0.  1.]
DescriptionPlain : [ "IN NEED OF A FOSTER HOME UNTIL I CAN BE ADOPTED!\r\nMy name is Nikita and I'm a&nbsp;distinguished gentleman approximately 7 years old.&nbsp; If you look deep into my eyes, you will see sadness.&nbsp;&nbsp;You see, I was adopted by a wonderful family 5 years ago but due to a family crisis, they had to return me to LSBR.&nbsp; I don't fault my family......they didn't want to have to give me up.&nbsp; I had a hard time adjusting when I first came back to LSBR but I&nbsp;have moved on.&nbsp;&nbsp;I'm putting all of my energy into&nbsp;finding another forever home just as fast as I can!\r\nHere's all you need to know about me:&nbsp; I'm a very loveable guy that's never met a stranger...that's to say I absolutely love people.&nbsp;&nbsp;I'm crate trained,&nbsp;house broken, and I get along&nbsp;well with&nbsp;other dogs.&nbsp; I have this adorably long tongue that hangs out of my mouth most of the time (take a look at my photos)......I think it gives me character!&nbsp; I love to go for car rides&nbsp;and would like nothing more than to take a ride right on to&nbsp;my new forever home!!!"
 "Hi! My name is Bianca, and if you can believe this, my mom is a boxer! (Obviously I take after my dad.) I am a sweet and healthy five-year-old girl, and pretty quiet most of the time. I love people, I really like my canine friends, and I seem to do okay with cats too!  The really good news is that I like my crate home, and I'm a real lady on the leash. Just like my brother Mick, who looks like me, I just want to find my own home. Please give me a chance to start a new life."
 "I'm Mick, and I think I'm pretty darn handsome for a five-year-old! Although my sister Bianca and I look just like our dad, our mom is a boxer. I have a clean bill of health from my vet, except for my Addison's disease...but I hope that's okay with you. I think that's a good thing, right? I like people a lot, and I'm really nice and friendly to everyone. I haven't been around that many other dogs yet, but I can't wait to meet some new friends! I love hanging out in my crate, and I do pretty well on a leash - taking walks is one of my favorite things to do. I've been told that I'm a typical teenager, though, and may need some additional training to make me just perfect. If you're looking for a great guy to hang around with, please look me up. I'm really ready to find a home of my own."
 ...,
 '&nbsp; This three month old Lab/Beagle mix is just a doll.&nbsp; Sugar is petite and most likely will always be a dainty girl.She has white on her chest and sprinkled on one foot.&nbsp; And she has two sisters who are just like her!&nbsp; This litter was an accident, but what an adorable mix resulted.&nbsp;&nbsp; They look like smaller Labs with long ears!&nbsp;&nbsp; And their dispositions are amazing -&nbsp; mellow, inquisitive, and happy all rolled into one great personality. The adoption fee of $125 includes a certificate to spay when they are older. '
 'Heather Allison- Lee called her in found at her mom&#39;s house at 437 S. Sycamore St. Flora.'
 'This dog was found in Centerton AR on 1/9/2015. He is a good dog, very friendly and affectionate. Would make a great pet.']
GeneralAge : ['Adult' 'Young' 'Unknown' 'Baby' 'Senior']
GeneralSizePotential : ['Medium' 'Unknown' 'Small' 'Large' 'X-Large']
Housetrained : ['1.0' 'Unknown' '0.0']
IndoorOutdoor : ['Indoor Only' 'Unknown' 'Indoor and Outdoor' 'Outdoor Only']
LocationState : ['TX' 'CA' 'IL' 'NC' 'PA' 'FL' 'MI' 'MD' 'WV' 'KY' 'TN' 'IN' 'DE' 'MO' 'OK'
 'VT' 'UT' 'WY' 'MN' 'LA' 'VA' 'NY' 'KS' 'MA' 'OH' 'MT' 'GA' 'AL' 'OR' 'SC'
 'ND' 'WA' 'CO' 'NJ' 'RI' 'WI' 'AR' 'AZ' 'IA' 'ME' 'SD' 'NS' 'ON' 'NM' 'NV'
 'NE' 'QC' 'MS' 'CT' 'AB' 'AK' 'ID' 'NH' 'DC' 'VI' 'BC' 'PR']
Microchipped : [0.0 1.0 '1.0' 'Unknown']
MixedBreed : [ 1.  0.]
NeedsFoster : [ 1.  0.]
NewPeople : ['Unknown' 'Friendly' 'Cautious' 'Protective' 'Aggressive']
NumPictures : [  5.           8.           9.           1.           3.           4.           2.
   6.          11.          13.          10.           7.          17.           0.
  12.          20.          15.          29.          14.          18.          22.
  21.          16.          34.          19.          36.          23.          28.
  26.          43.          30.          25.          24.          46.
   3.93576226  39.          27.          47.          35.          38.          31.
  40.          65.          45.          32.          33.          63.          51.
  41.          64.          48.          54.          49.          80.          53.        ]
NumVideos : [ 0.          1.          3.          2.          6.          4.          5.
  8.          0.04076985  7.        ]
OKWithCats : ['Unknown' '1.0' '0.0']
OKWithDogs : ['1.0' 'Unknown' '0.0']
OKWithKids : ['Unknown' '1.0' '0.0']
OrgID : [  884.  2215.  3119. ...,  4352.  4615.  3317.]
PrimaryBreed : ['Boxer' 'Labrador Retriever' 'Poodle (Toy)' 'Shetland Sheepdog Sheltie'
 'Siberian Husky' 'Terrier' 'Australian Shepherd' 'Golden Retriever'
 'Chihuahua' 'Shih Tzu' 'Poodle (Miniature)' 'Beagle' 'Shepherd'
 'American Eskimo Dog' 'Cairn Terrier' 'Yorkshire Terrier Yorkie'
 'Border Collie' 'Great Pyrenees' 'Rottweiler' 'Basset Hound'
 'German Shepherd Dog' 'Collie' 'Pomeranian' 'Black Labrador Retriever'
 'Yellow Labrador Retriever' 'Dachshund' 'Chocolate Labrador Retriever'
 'Doberman Pinscher' 'Corgi' 'Saint Bernard' 'Mastiff'
 'Black and Tan Coonhound' 'Pug' 'Great Dane' 'Hound' 'Pit Bull Terrier'
 'Cocker Spaniel' 'Miniature Pinscher' 'Newfoundland Dog'
 'Springer Spaniel' 'Border Terrier' 'Poodle (Standard)'
 'Petit Basset Griffon Vendeen' 'Irish Wolfhound' 'Cattle Dog' 'Havanese'
 'Australian Cattle Dog/Blue Heeler' 'Brussels Griffon'
 'Jack Russell Terrier' 'Fox Terrier' 'Husky' 'American Pit Bull Terrier'
 'Australian Kelpie' 'Parson Russell Terrier' 'Bullmastiff' 'Schnauzer'
 'Bichon Frise' 'Miniature Schnauzer' 'Belgian Shepherd Malinois' 'Bulldog'
 'American Staffordshire Terrier' 'Basenji' 'Alaskan Malamute' 'Spaniel'
 'Samoyed' 'Welsh Corgi' 'Papillon' 'Lhasa Apso' 'American Bulldog'
 'German Shorthaired Pointer' 'Poodle (unknown type)' 'Rat Terrier'
 'Rhodesian Ridgeback' 'Toy Terrier' 'Weimaraner' 'Bull Terrier'
 'Anatolian Shepherd' 'English Setter' 'Maltese' 'Manchester Terrier'
 'Queensland Heeler' 'German Wirehaired Pointer' 'Boston Terrier'
 'Italian Greyhound' 'Dalmatian' 'Staffordshire Bull Terrier'
 'Bluetick Coonhound' 'Retriever' 'Whippet' 'Bloodhound' 'Pointer'
 'Shar Pei' 'Airedale Terrier' 'Pembroke Welsh Corgi' 'Coton de Tulear'
 'Pekingese' 'Chinese Shar-Pei' 'Poodle (T-Cup)' 'Briard' 'Spitz'
 'Cockapoo' 'English Springer Spaniel' 'Flat-coated Retriever'
 'Treeing Walker Coonhound' 'Tibetan Spaniel'
 'Cavalier King Charles Spaniel'
 'Jack Russell Terrier (Parson Russell Terrier)' 'Neapolitan Mastiff'
 'Plott Hound' 'American Foxhound' 'Toy Fox Terrier'
 'West Highland White Terrier Westie' 'Setter' 'Catahoula Leopard Dog'
 'Wirehaired Fox Terrier' 'Black Mouth Cur' 'Keeshond' 'English Pointer'
 'Harrier' 'Irish Terrier' 'Bernese Mountain Dog' 'Shiba Inu'
 'Dogue de Bordeaux' 'Greyhound' 'Brittany' 'Bearded Collie'
 'Wire-haired Pointing Griffon' 'Wheaten Terrier' 'Norfolk Terrier'
 'White German Shepherd' 'Redbone Coonhound' 'English Bulldog'
 'German Spitz' 'Greater Swiss Mountain Dog' 'Cardigan Welsh Corgi' 'Akita'
 'Red Heeler' 'German Pinscher' 'Chinese Crested-Powder Puff' 'Elkhound'
 'Tibetan Terrier' 'Scottish Terrier Scottie' 'Chesapeake Bay Retriever'
 'Xoloitzcuintle/Mexican Hairless' 'Chow Chow' 'Mountain Cur'
 'Silky Terrier' 'Norwich Terrier' 'Old English Sheepdog' 'Affenpinscher'
 'Dutch Shepherd' 'English Cocker Spaniel' 'Smooth Fox Terrier' 'Coonhound'
 'Norwegian Elkhound' 'Eskimo Dog' 'Chinese Crested-Hairless'
 'Welsh Terrier' 'Australian Terrier' 'Mountain Dog' 'Lakeland Terrier'
 'Gordon Setter' 'Dandie Dinmont Terrier' 'Cane Corso Mastiff'
 'Belgian Shepherd Tervuren' 'American Hairless Terrier' 'Japanese Chin'
 'Otterhound' 'Leonberger' 'Vizsla' 'Feist' 'Lancashire Heeler'
 'Bedlington Terrier' 'Schipperke' 'Skye Terrier' 'French Mastiff'
 'English Shepherd' 'Presa Canario' 'Finnish Spitz' 'Carolina Dog' 'Biewer'
 'Canaan Dog' 'Soft-Coated Wheaten Terrier' 'Foxhound' 'Eskimo Spitz'
 'Tosa Inu' 'Tibetan Mastiff' 'Boykin Spaniel' 'Clumber Spaniel'
 'Dogo Argentino' 'Pharaoh Hound' 'French Bulldog' 'Jindo (Korean)'
 'Bouvier des Flandres' 'Scottish Deerhound' 'Kai Dog'
 'Portuguese Water Dog' 'Saluki' 'Sussex Spaniel' 'Ibizan Hound'
 'English Toy Spaniel' 'Sheep Dog' 'Irish Setter'
 'Nova Scotia Duck-Tolling Retriever' 'Boerboel Mastiff'
 'Kerry Blue Terrier' 'McNab' 'Giant Schnauzer' 'Podengo Portugueso'
 'American Water Spaniel' 'Patterdale Terrier (Fell Terrier)'
 'Thai Ridgeback' 'Maremma Sheepdog' 'Irish Water Spaniel'
 'Glen of Imaal Terrier' 'Welsh Springer Spaniel' 'Klee Kai'
 'Peruvian Inca Orchid' 'Italian Mastiff' 'Field Spaniel'
 'Karelian Bear Dog' 'Kuvasz' 'English Mastiff' 'Anatolian Karabash Dog'
 'Entlebucher' 'Bordeaux' 'Basset Griffon Vendeen' 'English Coonhound'
 'English Sheepdog' 'Blue Lacy' 'Afghan Hound' 'Borzoi'
 'Appenzell Mountain Dog' 'Deerhound' 'Bolognese' 'Finnish Lapphund'
 'Akbash' 'Wolf Dog' 'Italian Spinone' 'Belgian Shepherd Dog Sheepdog'
 'Pumi' 'Munsterlander' 'Sealyham Terrier' 'Puli' 'Saluki Greyhound'
 'Spinone Italiano' 'Curly-Coated Retriever' 'Kishu' 'English Foxhound'
 'Hovawart' 'Alaskan Klee Kai' 'Hollandse Tulphond'
 'White Swiss Shepherd Dog (Swiss Berger)' 'Swedish Vallhund'
 'Mexican Hairless' 'Polish Lowland Sheepdog' 'Miniature Bull Terrier'
 'Beauceron' 'Fila Brasileiro' 'French Brittany'
 'Belgian Shepherd Laekenois' 'Galgo Spanish Greyhound' 'Picardy Shepherd'
 'Saarlooswolfhond' 'Norwegian Buhund' 'L\xc3\xb6wchen' 'Komondor'
 'Spanish Mastiff']
SearchString : ['Nikita    Male Medium   Dogs Boxers'
 'Bianca  Black Black Female Medium  Black Dogs Labrador Retriever / Boxer / Mixeds'
 'Mick    Male Medium   Dogs Labrador Retriever / Boxer / Mixeds' ...,
 'Sugar   Black with White Female Medium   Dogs Black Labrador Retriever / Beagle / Mixed (medium coat)s'
 'Lacey (pitbull-female)   Black with White Female Medium   Dogs American Pit Bull Terrier (short coat)s'
 '15-4                   WILEY   White Male Medium 15-5  Dogs American Eskimo Dog (long coat)s']
SecondaryBreed : ['Unknown' 'Boxer' 'Australian Shepherd'
 'Australian Cattle Dog/Blue Heeler' 'Shih Tzu' 'Terrier' 'Poodle (Toy)'
 'Labrador Retriever' 'Spitz' 'Pit Bull Terrier' 'Chow Chow' 'Beagle'
 'Papillon' 'Spaniel' 'Chihuahua' 'Belgian Shepherd Malinois'
 'American Foxhound' 'Golden Retriever' 'Schnauzer' 'Border Collie'
 'Rottweiler' 'Shepherd' 'Poodle (Miniature)' 'German Shepherd Dog' 'Corgi'
 'Shetland Sheepdog Sheltie' 'American Bulldog' 'Cattle Dog'
 'Jack Russell Terrier' 'Dachshund' 'Bloodhound' 'Catahoula Leopard Dog'
 'Collie' 'Shar Pei' 'Neapolitan Mastiff'
 'Jack Russell Terrier (Parson Russell Terrier)' 'Mastiff' 'Pug'
 'Cocker Spaniel' 'Great Pyrenees' 'Whippet' 'Maltese' 'Hound' 'Dalmatian'
 'Black Labrador Retriever' 'Queensland Heeler' 'Yellow Labrador Retriever'
 'Retriever' 'Saint Bernard' 'Greyhound' 'Basenji' 'Pointer'
 'Silky Terrier' 'Welsh Corgi' 'Bulldog' 'Rat Terrier'
 'Yorkshire Terrier Yorkie' 'Weimaraner' 'Wirehaired Fox Terrier' 'Setter'
 'Lhasa Apso' 'Boston Terrier' 'Chocolate Labrador Retriever' 'Husky'
 'Airedale Terrier' 'Pekingese' 'Rhodesian Ridgeback' 'Newfoundland Dog'
 'Siberian Husky' 'French Bulldog' 'American Pit Bull Terrier'
 'Australian Kelpie' 'Pomeranian' 'German Shorthaired Pointer'
 'Mountain Cur' 'Bichon Frise' 'Fox Terrier' 'Chinese Shar-Pei'
 'West Highland White Terrier Westie' 'Redbone Coonhound'
 'Greater Swiss Mountain Dog' 'Poodle (unknown type)' 'Affenpinscher'
 'Bluetick Coonhound' 'Basset Hound' 'Doberman Pinscher'
 'Poodle (Standard)' 'Springer Spaniel' 'Poodle (T-Cup)' 'English Setter'
 'Canaan Dog' 'Presa Canario' 'Great Dane' 'American Staffordshire Terrier'
 'Cockapoo' 'Brittany' 'Cavalier King Charles Spaniel' 'Wheaten Terrier'
 'Toy Fox Terrier' 'Boykin Spaniel' 'Anatolian Shepherd' 'Brussels Griffon'
 'Cairn Terrier' 'Leonberger' 'Scottish Terrier Scottie'
 'Nova Scotia Duck-Tolling Retriever' 'Italian Greyhound' 'Norwich Terrier'
 'Schipperke' 'Plott Hound' 'Smooth Fox Terrier'
 'Soft-Coated Wheaten Terrier' 'Bearded Collie' 'Treeing Walker Coonhound'
 'Miniature Pinscher' 'Chesapeake Bay Retriever' 'Toy Terrier'
 'Tibetan Spaniel' 'English Toy Spaniel' 'Foxhound' 'Tibetan Terrier'
 'Feist' 'Harrier' 'Manchester Terrier' 'Shiba Inu'
 'Staffordshire Bull Terrier' 'Havanese' 'Dogo Argentino' 'Saluki'
 'English Shepherd' 'English Pointer' 'Bull Terrier'
 'Chinese Crested-Powder Puff' 'Flat-coated Retriever' 'Vizsla'
 'American Eskimo Dog' 'Belgian Shepherd Tervuren' 'Irish Terrier'
 'Miniature Schnauzer' 'Pembroke Welsh Corgi' 'Australian Terrier'
 'Bullmastiff' 'Border Terrier' 'McNab' 'Parson Russell Terrier' 'Keeshond'
 'Cardigan Welsh Corgi' 'Welsh Terrier' 'Black and Tan Coonhound' 'Samoyed'
 'Chinese Crested-Hairless' 'German Wirehaired Pointer' 'Dutch Shepherd'
 'English Coonhound' 'Norwegian Elkhound' 'Coonhound' 'Alaskan Malamute'
 'Akita' 'Scottish Deerhound' 'Red Heeler' 'German Spitz' 'Jindo (Korean)'
 'Carolina Dog' 'Irish Wolfhound' 'Cane Corso Mastiff' 'Japanese Chin'
 'French Mastiff' 'Glen of Imaal Terrier' 'Italian Mastiff'
 'Black Mouth Cur' 'Clumber Spaniel' 'Norfolk Terrier' 'Finnish Lapphund'
 'English Bulldog' 'Xoloitzcuintle/Mexican Hairless'
 'White German Shepherd' 'Bernese Mountain Dog'
 'Wire-haired Pointing Griffon' 'Otterhound' 'Irish Setter'
 'L\xc3\xb6wchen' 'Maremma Sheepdog' 'Petit Basset Griffon Vendeen'
 'Sheep Dog' 'Sussex Spaniel' 'Kuvasz' 'Belgian Shepherd Dog Sheepdog'
 'Norwegian Buhund' 'Lancashire Heeler' 'Ibizan Hound' 'Skye Terrier'
 'Giant Schnauzer' 'Coton de Tulear' 'Pharaoh Hound' 'Old English Sheepdog'
 'Black Russian Terrier' 'Finnish Spitz' 'Polish Lowland Sheepdog' 'Akbash'
 'English Springer Spaniel' 'Entlebucher'
 'Patterdale Terrier (Fell Terrier)' 'English Foxhound' 'Eskimo Dog'
 'Bouvier des Flandres' 'Briard' 'Wolf Dog' 'Peruvian Inca Orchid'
 'English Mastiff' 'Boerboel Mastiff' 'Mountain Dog' 'Sealyham Terrier'
 'Dogue de Bordeaux' 'Munsterlander' 'Portuguese Water Dog'
 'Miniature Bull Terrier' 'Chinook' 'Beauceron' 'Gordon Setter'
 'English Cocker Spaniel' 'American Water Spaniel' 'Dandie Dinmont Terrier'
 'Blue Lacy' 'Deerhound' 'German Pinscher' 'Hovawart' 'Argentinian Mastiff'
 'Mexican Hairless' 'Elkhound' 'Bolognese' 'Eskimo Spitz' 'Field Spaniel'
 'Curly-Coated Retriever' 'Kerry Blue Terrier' 'Tibetan Mastiff'
 'Karelian Bear Dog' 'Bedlington Terrier' 'Borzoi' 'Klee Kai'

In [92]:
test_df = dummify(r_df, ['ActivityLevel', 'GeneralAge', 'GeneralSizePotential', 'Housetrained', 'IndoorOutdoor'],
                  ['Moderately Active', 'Adult', 'Medium', 'Unknown', 'Unknown'])

In [97]:
r_df.to_csv('data/data_without_dummies.csv')

In [94]:
r_df = pd.read_csv('data/data_without_dummies.csv')

In [91]:
def dummify(df, fields, baselines):
    for i, field in enumerate(fields):
        dummies = pd.get_dummies(df[field])
        cols = dummies.columns.values
        keep_cols = cols[cols!=baselines[i]]
        new_cols = [field + "_"+ col_name for col_name in keep_cols]
        df[new_cols] = dummies[keep_cols]
        del df[field]
    return df

In [93]:
test_df.columns

Index([u'Unnamed: 0', u'AdoptionFee', u'Altered', u'BiggestPictures',
       u'BiggestVideos', u'Breed', u'Color', u'Declawed', u'DescriptionPlain',
       u'GeneralAge', u'GeneralSizePotential', u'Housetrained',
       u'IndoorOutdoor', u'LocationState', u'Microchipped', u'MixedBreed',
       u'NeedsFoster', u'NewPeople', u'NumPictures', u'NumVideos',
       u'OKWithCats', u'OKWithDogs', u'OKWithKids', u'OrgID', u'PrimaryBreed',
       u'SearchString', u'SecondaryBreed', u'Sex', u'SizeCurrent',
       u'SizePotential', u'Specialneeds', u'Uptodate', u'Start_Date',
       u'End_Date', u'Adopted', u'Censored', u'Time', u'Age_at_Start',
       u'Has_url', u'In_Foster', u'Mostly_Black', u'Region',
       u'Search_String_Num_Terms', u'Description_Length', u'Desc_Latent_Topic',
       u'Has_Video', u'Pitbull', u'Terrier', u'Hound', u'Herding', u'Working',
       u'Breed_Group', u'ActivityLevel_Highly Active',
       u'ActivityLevel_Not Active', u'ActivityLevel_Slightly Active',
       u'ActivityLevel_Unknown'],
      dtype='object')

In [95]:
r_df['GoodShelter'] = df['OrgID'].apply(lambda x: 1 if x==993
                                       else 1 if x==3182
                                       else 0)

r_df['BadShelter'] = df['OrgID'].apply(lambda x: 1 if x==1833
                                       else 1 if x==2478
                                       else 0)

In [96]:
r_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152259 entries, 0 to 152258
Data columns (total 55 columns):
Unnamed: 0                 152259 non-null int64
ActivityLevel              152259 non-null object
AdoptionFee                152259 non-null float64
Altered                    152259 non-null float64
BiggestPictures            152259 non-null float64
BiggestVideos              152259 non-null float64
Breed                      152259 non-null object
Color                      152259 non-null object
Declawed                   152259 non-null float64
DescriptionPlain           143750 non-null object
GeneralAge                 152259 non-null object
GeneralSizePotential       152259 non-null object
Housetrained               152259 non-null object
IndoorOutdoor              152259 non-null object
LocationState              152259 non-null object
Microchipped               152259 non-null object
MixedBreed                 152259 non-null float64
NeedsFoster                152259 non-null float64
NewPeople                  152259 non-null object
NumPictures                152259 non-null float64
NumVideos                  152259 non-null float64
OKWithCats                 152259 non-null object
OKWithDogs                 152259 non-null object
OKWithKids                 152259 non-null object
OrgID                      152259 non-null float64
PrimaryBreed               152259 non-null object
SearchString               152259 non-null object
SecondaryBreed             152259 non-null object
Sex                        152259 non-null object
SizeCurrent                136372 non-null float64
SizePotential              121449 non-null float64
Specialneeds               152259 non-null float64
Uptodate                   152259 non-null float64
Start_Date                 152259 non-null object
End_Date                   152259 non-null object
Adopted                    152259 non-null int64
Censored                   152259 non-null int64
Time                       152259 non-null int64
Age_at_Start               128743 non-null float64
Has_url                    152259 non-null int64
In_Foster                  152259 non-null int64
Mostly_Black               152259 non-null int64
Region                     152259 non-null object
Search_String_Num_Terms    152259 non-null int64
Description_Length         152259 non-null int64
Desc_Latent_Topic          152259 non-null int64
Has_Video                  152259 non-null int64
Pitbull                    152259 non-null int64
Terrier                    152259 non-null int64
Hound                      152259 non-null int64
Herding                    152259 non-null int64
Working                    152259 non-null int64
Breed_Group                152259 non-null object
GoodShelter                152259 non-null int64
BadShelter                 152259 non-null int64
dtypes: float64(15), int64(18), object(22)
memory usage: 63.9+ MB

In [99]:
r_df[r_df['BadShelter']==1]

,Unnamed: 0,ActivityLevel,AdoptionFee,Altered,BiggestPictures,BiggestVideos,Breed,Color,Declawed,DescriptionPlain,...,Desc_Latent_Topic,Has_Video,Pitbull,Terrier,Hound,Herding,Working,Breed_Group,GoodShelter,BadShelter
85209,85209,Unknown,265.08532,1.0,49632.000000,0.000000,Terrier / Mixed (short coat),"White with Tan, Yellow or Fawn",0.0,"Katrina and her brother, Toby, were found by a...",...,3,0,0,1,0,0,0,Terrier,0,1
85210,85210,Unknown,265.08532,1.0,29299.000000,0.000000,Terrier / Mixed (short coat),Black with White,0.0,"Toby&nbsp;and his sister, Katrina, were found ...",...,0,0,0,1,0,0,0,Terrier,0,1
85211,85211,Unknown,265.08532,1.0,23688.000000,0.000000,Shepherd / Mixed (medium coat),White,0.0,Lady was picked up stray on 07/31/09.&nbsp; Si...,...,3,0,0,0,0,1,0,Herding,0,1
85212,85212,Unknown,265.08532,1.0,39980.000000,0.000000,Terrier / Mixed (medium coat),Golden/Chestnut,0.0,Amy is a 3 yo female terrier mix. She was foun...,...,3,0,0,1,0,0,0,Terrier,0,1
85215,85215,Unknown,265.08532,1.0,43554.000000,0.000000,Brussels Griffon (medium coat),Tan/Yellow/Fawn with Black,0.0,This girl came in from her owners as a release...,...,3,0,0,0,0,0,0,Other,0,1
85217,85217,Unknown,265.08532,1.0,39866.000000,0.000000,Labrador Retriever (short coat),Tan,0.0,CLIVE IS A 1 YEAR OLD yellowLAB.&nbsp; HE IS A...,...,3,0,0,0,0,0,1,Working,0,1
85219,85219,Unknown,265.08532,1.0,51032.000000,0.000000,Labrador Retriever (short coat),Tan/Yellow/Fawn with White,0.0,"PATSY IS A 1 YEAR OLD, TAN AND WHITE, FEMALE L...",...,3,0,0,0,0,0,1,Working,0,1
85221,85221,Unknown,265.08532,1.0,32645.000000,0.000000,Poodle (Miniature) (short coat),White,0.0,Gus was found as a stray.. He is a tiny thing ...,...,3,0,0,0,0,0,0,Other,0,1
85222,85222,Unknown,265.08532,1.0,33370.000000,0.000000,Labrador Retriever / Mixed (medium coat),Black with Gray or Silver,0.0,This sweetie was found underneath a moble home...,...,3,0,0,0,0,0,1,Working,0,1
85226,85226,Unknown,265.08532,1.0,49975.000000,0.000000,American Bulldog / American Pit Bull Terrier (...,Red/Golden/Orange/Chestnut with White,0.0,Cherry is a very sweet girl to humans. She doe...,...,3,0,1,1,0,0,0,Pitbull,0,1
85227,85227,Unknown,265.08532,1.0,53578.000000,0.000000,Labrador Retriever / Red Heeler / Mixed (short...,"White with Red, Golden, Orange or Chestnut",0.0,Bart is a female 5 mo lab mix. He was found in...,...,3,0,0,0,0,0,1,Working,0,1
85230,85230,Unknown,265.08532,1.0,60149.000000,0.000000,German Shepherd Dog / Mixed (medium coat),Tricolor (Tan/Brown & Black & White),0.0,This little girl is about a year old. She is v...,...,3,0,0,0,0,1,0,Herding,0,1
85231,85231,Unknown,265.08532,1.0,38682.000000,0.000000,Australian Shepherd / Mixed (medium coat),Tricolor (Tan/Brown & Black & White),0.0,Honey Bun&nbsp;was originally&nbsp;saved by a ...,...,0,0,0,0,0,1,0,Herding,0,1
85233,85233,Unknown,265.08532,1.0,37345.000000,0.000000,Jack Russell Terrier (short coat),Tricolor (Tan/Brown & Black & White),0.0,Natal is a super sweet jack Russell Terrier. S...,...,3,0,0,1,0,0,0,Terrier,0,1
85235,85235,Unknown,265.08532,1.0,42385.000000,0.000000,Dachshund / Boston Terrier / Mixed (short coat),Black with White,0.0,"Hi, my name is Flower. I was found at the back...",...,3,0,0,1,1,0,0,Terrier,0,1
85238,85238,Unknown,265.08532,1.0,34474.000000,0.000000,Chihuahua / Miniature Pinscher (short coat),Brown/Chocolate with Tan,0.0,"Meet Ruby, the gem of the day! Ruby is a 3 yea...",...,3,0,0,0,0,0,0,Other,0,1
85248,85248,Unknown,265.08532,1.0,38012.000000,0.000000,Boxer / Labrador Retriever / Mixed (short coat),Brindle,0.0,Kenzie was picked up stray on 07/31/09.&nbsp; ...,...,3,0,0,0,0,0,1,Working,0,1
85249,85249,Unknown,265.08532,1.0,45443.000000,0.000000,Chihuahua (short coat),Tan/Yellow/Fawn with White,0.0,"Meet Ginger, the spice of the day!&nbsp;Ginger...",...,3,0,0,0,0,0,0,Other,0,1
85250,85250,Unknown,265.08532,1.0,39028.000000,0.000000,Cocker Spaniel (medium coat),Brown/Chocolate with Tan,0.0,Princess is a 5 year old Cocker Spaniel. She w...,...,3,0,0,0,0,0,1,Working,0,1
85251,85251,Unknown,265.08532,1.0,29398.000000,0.000000,Labrador Retriever / Shepherd / Mixed (short c...,"Black with Tan, Yellow or Fawn",0.0,Ziggy was picked up stray on 08/05/09.&nbsp; S...,...,3,0,0,0,0,1,1,Herding,0,1
85252,85252,Unknown,265.08532,1.0,54254.000000,0.000000,Labrador Retriever / Mixed (short coat),White with Black,0.0,Binx was picked up stray on 08/05/09.&nbsp; Si...,...,0,0,0,0,0,0,1,Working,0,1
85254,85254,Unknown,265.08532,1.0,59723.000000,0.000000,Pug / Chihuahua / Mixed (short coat),Brown/Chocolate with Black,0.0,"Found at the end&nbsp; of a drive way, this fu...",...,3,0,0,0,0,0,0,Other,0,1
85255,85255,Unknown,265.08532,1.0,82936.000000,0.000000,Pug / Chihuahua / Mixed (short coat),"Black with Tan, Yellow or Fawn",0.0,"Found at the end&nbsp; of a drive way, this fu...",...,3,0,0,0,0,0,0,Other,0,1
85258,85258,Unknown,265.08532,1.0,24983.000000,0.000000,Labrador Retriever (short coat),Black with White,0.0,"Zorie was found as a stray with her brother, S...",...,3,0,0,0,0,0,1,Working,0,1
85262,85262,Unknown,265.08532,1.0,41266.000000,0.000000,Pomeranian (long coat),Red/Golden/Orange/Chestnut with White,0.0,"Christine is a&nbsp;5 year old, well rounded p...",...,3,0,0,0,0,0,0,Other,0,1
85263,85263,Unknown,265.08532,1.0,0.000000,0.000000,German Shepherd Dog (short coat),Tan/Yellow/Fawn with White,0.0,NaN,...,0,0,0,0,0,1,0,Herding,0,1
85265,85265,Unknown,265.08532,1.0,33555.000000,0.000000,Schnauzer / Mixed (medium coat),Gray/Silver/Salt & Pepper with White,0.0,"Hi there, how are you? I am so happy to meet y...",...,3,0,0,0,0,0,0,Other,0,1
85269,85269,Unknown,265.08532,1.0,29244.000000,0.000000,Chihuahua (short coat),Red/Golden/Orange/Chestnut with White,0.0,"My name is Chance, and I am about 4 years old....",...,3,0,0,0,0,0,0,Other,0,1
85271,85271,Unknown,265.08532,1.0,47335.000000,0.000000,Labrador Retriever (short coat),Black,0.0,Kassie was picked up 08/05/09.&nbsp; We do not...,...,3,0,0,0,0,0,1,Working,0,1
85273,85273,Unknown,265.08532,1.0,45130.000000,0.000000,Dalmatian / Mixed (short coat),White with Black,0.0,Have you ever seen something as cute as me? I ...,...,3,0,0,0,0,0,0,Other,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152156,152156,Unknown,265.08532,1.0,68914.899703,287575.499262,Chihuahua (short coat),Black with White,0.0,\r\nHiya! My name is Minnie! I had been hiding...,...,0,0,0,0,0,0,0,Other,0,1
152158,152158,Unknown,265.08532,1.0,68914.899703,287575.499262,Silky Terrier / Schnauzer / Mixed (medium coat),Gray/Silver/Salt & Pepper with White,0.0,"\r\nEric is an owner surrender, due to his eld...",...,0,0,0,1,0,0,0,Terrier,0,1
152159,152159,Unknown,265.08532,1.0,68914.899703,287575.499262,German Wirehaired Pointer / Black Labrador Ret...,Black with White,0.0,\r\n&nbsp;\r\nThese pups came to us with their...,...,0,0,0,0,0,0,1,Working,0,1
152160,152160,Unknown,265.08532,1.0,68914.899703,287575.499262,German Wirehaired Pointer / Black Labrador Ret...,Black with White,0.0,\r\nThese pups came to us with their mom Heidi...,...,0,0,0,0,0,0,1,Working,0,1
152161,152161,Unknown,265.08532,1.0,68914.899703,287575.499262,German Wirehaired Pointer / Black Labrador Ret...,Black with White,0.0,\r\nThese pups came to us with their mom Heidi...,...,0,0,0,0,0,0,1,Working,0,1
152162,152162,Unknown,265.08532,1.0,68914.899703,287575.499262,German Wirehaired Pointer / Black Labrador Ret...,Black with White,0.0,\r\nThese pups came to us with their mom Heidi...,...,0,0,0,0,0,0,1,Working,0,1
152163,152163,Unknown,265.08532,1.0,68914.899703,287575.499262,German Wirehaired Pointer / Black Labrador Ret...,Black with White,0.0,\r\nThese pups came to us with their mom Heidi...,...,0,0,0,0,0,0,1,Working,0,1
152164,152164,Unknown,265.08532,1.0,68914.899703,287575.499262,German Wirehaired Pointer / Black Labrador Ret...,Black with White,0.0,\r\nThese pups came to us with their mom Heidi...,...,0,0,0,0,0,0,1,Working,0,1
152166,152166,Unknown,265.08532,1.0,68914.899703,287575.499262,German Wirehaired Pointer / Black Labrador Ret...,White with Black,0.0,\r\nThese pups came to us with their mom Heidi...,...,0,0,0,0,0,0,1,Working,0,1
152167,152167,Unknown,265.08532,1.0,68914.899703,287575.499262,German Wirehaired Pointer / Black Labrador Ret...,White with Black,0.0,\r\nThese pups came to us with their mom Heidi...,...,0,0,0,0,0,0,1,Working,0,1
152168,152168,Unknown,265.08532,1.0,68914.899703,287575.499262,German Wirehaired Pointer / Black Labrador Ret...,Black with White,0.0,\r\nThese pups came to us with their mom Heidi...,...,0,0,0,0,0,0,1,Working,0,1
152169,152169,Unknown,265.08532,1.0,68914.899703,287575.499262,German Wirehaired Pointer / Black Labrador Ret...,Black with White,0.0,\r\nThese pups came to us with their mom Heidi...,...,0,0,0,0,0,0,1,Working,0,1
152170,152170,Unknown,265.08532,1.0,68914.899703,287575.499262,German Wirehaired Pointer / Black Labrador Ret...,White with Black,0.0,\r\nThese pups came to us with their mom Heidi...,...,0,0,0,0,0,0,1,Working,0,1
152179,152179,Unknown,265.08532,1.0,68914.899703,287575.499262,Australian Cattle Dog/Blue Heeler / Border Col...,Black with White,0.0,\r\nSis is a smart dog who is loyal and wants ...,...,0,0,0,0,0,1,0,Herding,0,1
152184,152184,Unknown,265.08532,1.0,68914.899703,287575.499262,Dachshund / Chihuahua / Mixed (short coat),Tan/Yellow/Fawn with White,0.0,"\r\nEmmy is a sweet little doxi mix, who was f...",...,0,0,0,0,1,0,0,Hound,0,1
152185,152185,Unknown,265.08532,1.0,68914.899703,287575.499262,Schnauzer / Yorkshire Terrier Yorkie / Mixed (...,Black with Gray or Silver,0.0,\r\nAre you looking for a great little country...,...,3,0,0,1,0,0,0,Terrier,0,1
152186,152186,Unknown,265.08532,1.0,68914.899703,287575.499262,Yorkshire Terrier Yorkie (medium coat),Silver & Tan (Yorkie colors),0.0,\r\nNoel is a sweet and petite little dog. She...,...,3,0,0,1,0,0,0,Terrier,0,1
152187,152187,Unknown,265.08532,1.0,68914.899703,287575.499262,Pomeranian / Yorkshire Terrier Yorkie / Mixed ...,"Black with Tan, Yellow or Fawn",0.0,\r\n&nbsp;\r\nThis teenie tiny little lady was...,...,0,0,0,1,0,0,0,Terrier,0,1
152188,152188,Unknown,265.08532,1.0,68914.899703,287575.499262,Shar Pei / Border Collie / Mixed (short coat),Black with White,0.0,"\r\nOh my goodness, have you ever seen such an...",...,0,0,0,0,0,1,0,Herding,0,1
152202,152202,Unknown,265.08532,1.0,68914.899703,287575.499262,German Shepherd Dog (short coat),"Black with Tan, Yellow or Fawn",0.0,\r\nHI my name is Kelly. I was found out wande...,...,0,0,0,0,0,1,0,Herding,0,1
152203,152203,Unknown,265.08532,1.0,68914.899703,287575.499262,Boxer (short coat),Brindle,0.0,"\r\nBoxer lovers beware, Bindy is adorable!! S...",...,0,0,0,0,0,0,0,Other,0,1
152204,152204,Unknown,265.08532,1.0,68914.899703,287575.499262,Australian Shepherd (short coat),Merle,0.0,\r\nBuffy was born 8-16-14 &nbsp;into a litter...,...,0,0,0,0,0,1,0,Herding,0,1
152205,152205,Unknown,265.08532,1.0,68914.899703,287575.499262,Miniature Pinscher / Mixed (short coat),Red,0.0,\r\n&nbsp;\r\nHiya! My name is Noodles! I am 1...,...,0,0,0,0,0,0,0,Other,0,1
152206,152206,Unknown,265.08532,1.0,68914.899703,287575.499262,Rottweiler / German Shepherd Dog / Mixed (shor...,"Black with Brown, Red, Golden, Orange or Chestnut",0.0,"\r\nAre you looking for a bog, goofy, affectio...",...,0,0,0,0,0,1,0,Herding,0,1
152229,152229,Unknown,265.08532,1.0,68914.899703,287575.499262,Cavalier King Charles Spaniel / Pekingese / Mi...,Tricolor (Tan/Brown & Black & White),0.0,\r\nHow can you not fall in love with those ey...,...,0,0,0,0,0,0,1,Working,0,1
152240,152240,Unknown,265.08532,1.0,68914.899703,287575.499262,Pomeranian / Chihuahua / Mixed (medium coat),"White with Tan, Yellow or Fawn",0.0,\r\nRain was a stray that had been seen runnin...,...,0,0,0,0,0,0,0,Other,0,1
152250,152250,Unknown,265.08532,1.0,68914.899703,287575.499262,Shih Tzu / Terrier / Mixed (medium coat),Silver & Tan (Yorkie colors),0.0,"\r\nArtie, Daisy and Pete are 3 cuties who wer...",...,0,0,0,1,0,0,0,Terrier,0,1
152251,152251,Unknown,265.08532,1.0,68914.899703,287575.499262,Shih Tzu / Yorkshire Terrier Yorkie / Mixed (m...,"White with Tan, Yellow or Fawn",0.0,"\r\n&nbsp;Daisy, Artie, and Pete are 3 cuties ...",...,0,0,0,1,0,0,0,Terrier,0,1
152252,152252,Unknown,265.08532,1.0,68914.899703,287575.499262,Border Collie / Flat-coated Retriever / Mixed ...,Black,0.0,"\r\n&nbsp;\r\n&nbsp;href=""&lt;img""&gt;http...",...,0,0,0,0,0,1,1,Herding,0,1
152253,152253,Unknown,265.08532,1.0,68914.899703,287575.499262,Black Labrador Retriever (short coat),Black,0.0,"\r\nHi, my name is Maverick. I am a big, hands...",...,0,0,0,0,0,0,1,Working,0,1

In [100]:
r_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152259 entries, 0 to 152258
Data columns (total 55 columns):
Unnamed: 0                 152259 non-null int64
ActivityLevel              152259 non-null object
AdoptionFee                152259 non-null float64
Altered                    152259 non-null float64
BiggestPictures            152259 non-null float64
BiggestVideos              152259 non-null float64
Breed                      152259 non-null object
Color                      152259 non-null object
Declawed                   152259 non-null float64
DescriptionPlain           143750 non-null object
GeneralAge                 152259 non-null object
GeneralSizePotential       152259 non-null object
Housetrained               152259 non-null object
IndoorOutdoor              152259 non-null object
LocationState              152259 non-null object
Microchipped               152259 non-null object
MixedBreed                 152259 non-null float64
NeedsFoster                152259 non-null float64
NewPeople                  152259 non-null object
NumPictures                152259 non-null float64
NumVideos                  152259 non-null float64
OKWithCats                 152259 non-null object
OKWithDogs                 152259 non-null object
OKWithKids                 152259 non-null object
OrgID                      152259 non-null float64
PrimaryBreed               152259 non-null object
SearchString               152259 non-null object
SecondaryBreed             152259 non-null object
Sex                        152259 non-null object
SizeCurrent                136372 non-null float64
SizePotential              121449 non-null float64
Specialneeds               152259 non-null float64
Uptodate                   152259 non-null float64
Start_Date                 152259 non-null object
End_Date                   152259 non-null object
Adopted                    152259 non-null int64
Censored                   152259 non-null int64
Time                       152259 non-null int64
Age_at_Start               128743 non-null float64
Has_url                    152259 non-null int64
In_Foster                  152259 non-null int64
Mostly_Black               152259 non-null int64
Region                     152259 non-null object
Search_String_Num_Terms    152259 non-null int64
Description_Length         152259 non-null int64
Desc_Latent_Topic          152259 non-null int64
Has_Video                  152259 non-null int64
Pitbull                    152259 non-null int64
Terrier                    152259 non-null int64
Hound                      152259 non-null int64
Herding                    152259 non-null int64
Working                    152259 non-null int64
Breed_Group                152259 non-null object
GoodShelter                152259 non-null int64
BadShelter                 152259 non-null int64
dtypes: float64(15), int64(18), object(22)
memory usage: 63.9+ MB

In [101]:
r_df['DescriptionPlain'].fillna(' ', inplace=True)

In [105]:
r_df[pd.isnull(r_df['SizeCurrent'])]

       GeneralAge GeneralSizePotential
368         Adult                Large
440         Young               Medium
559         Young                Small
1142        Young               Medium
1146        Adult               Medium
1178        Adult                Large
1292        Adult               Medium
1438         Baby               Medium
1578         Baby               Medium
1607        Young                Large
1693         Baby                Large
1812        Adult                Small
2098         Baby                Small
2457        Adult               Medium
2752        Young               Medium
3162        Young               Medium
3194        Adult                Large
3552         Baby               Medium
4077         Baby               Medium
4081        Adult               Medium
4125        Young               Medium
4130        Young               Medium
4338         Baby               Medium
4339         Baby               Medium
4513      Unknown                Small
4567         Baby               Medium
4574         Baby               Medium
4634        Young                Large
4751         Baby               Medium
4793        Adult               Medium
...           ...                  ...
151699      Adult               Medium
151876     Senior               Medium
151915       Baby                Small
151916       Baby                Small
151922      Young                Small
151933      Young               Medium
151967      Adult                Small
152044      Adult               Medium
152046      Adult                Large
152051      Adult               Medium
152081      Adult                Small
152110      Young               Medium
152114      Adult               Medium
152126      Adult                Small
152127      Young               Medium
152130      Young               Medium
152141      Young               Medium
152145      Young               Medium
152180       Baby               Medium
152182       Baby               Medium
152183       Baby               Medium
152189      Adult               Medium
152218       Baby               Medium
152220      Young               Medium
152236      Adult               Medium
152242       Baby               Medium
152246      Adult                Large
152248       Baby                Large
152255      Adult                Large
152257      Young               Medium

[15887 rows x 2 columns]

In [106]:
r_df['tempAgeSize'] = r_df['GeneralAge'] + r_df['GeneralSizePotential']

In [117]:
temp = r_df[['tempAgeSize', 'SizeCurrent', 'SizePotential']].groupby(['tempAgeSize']).agg(['mean'])
temp.reset_index()

       tempAgeSize SizeCurrent SizePotential
                          mean          mean
0       AdultLarge   41.910282     14.522992
1      AdultMedium   25.405390     10.479638
2       AdultSmall   10.430774      3.270100
3     AdultUnknown   21.707354      4.467046
4     AdultX-Large   78.469757     32.100899
5        BabyLarge   10.074036     25.458030
6       BabyMedium    8.378005     17.574978
7        BabySmall    4.627640      7.332918
8      BabyUnknown    4.396051      5.400424
9      BabyX-Large   17.725830     57.313800
10     SeniorLarge   47.730123     12.093686
11    SeniorMedium   29.107797      8.775580
12     SeniorSmall    8.958371      2.709912
13   SeniorUnknown   17.216316      3.063433
14   SeniorX-Large   83.407634     32.459459
15    UnknownLarge   26.316774     20.674484
16   UnknownMedium   15.203231     14.167982
17    UnknownSmall    7.616504      5.719195
18  UnknownUnknown   12.275994      3.084447
19  UnknownX-Large   59.532258     31.729508
20      YoungLarge   34.269701     18.786338
21     YoungMedium   23.700970     14.040192
22      YoungSmall   10.119832      4.003566
23    YoungUnknown   15.576510      5.078101
24    YoungX-Large   68.402905     42.514329

In [138]:
temp.columns = ['tempAgeSize', 'SizeCurrent_mean', 'SizePotential_mean']

In [111]:
test_df = r_df.copy()

In [139]:
result = pd.merge(test_df, temp, how='left', on=['tempAgeSize'])

In [140]:
result.head()

,Unnamed: 0,ActivityLevel,AdoptionFee,Altered,BiggestPictures,BiggestVideos,Breed,Color,Declawed,DescriptionPlain,...,Terrier,Hound,Herding,Working,Breed_Group,GoodShelter,BadShelter,tempAgeSize,SizeCurrent_mean,SizePotential_mean
0,0,Unknown,265.08532,1.0,96769.0,0.0,Boxer,Unknown,0.0,IN NEED OF A FOSTER HOME UNTIL I CAN BE ADOPTE...,...,0,0,0,0,Other,0,0,AdultMedium,25.405390,10.479638
1,1,Moderately Active,265.08532,1.0,95768.0,0.0,Labrador Retriever / Boxer / Mixed,Black,0.0,"Hi! My name is Bianca, and if you can believe ...",...,0,0,0,1,Working,0,0,AdultMedium,25.405390,10.479638
2,2,Moderately Active,265.08532,1.0,98461.0,0.0,Labrador Retriever / Boxer / Mixed,Unknown,0.0,"I'm Mick, and I think I'm pretty darn handsome...",...,0,0,0,1,Working,0,0,YoungMedium,23.700970,14.040192
3,3,Unknown,265.08532,1.0,84752.0,0.0,Boxer,Unknown,0.0,IN NEED OF FOSTER CARE UNTIL I CAN BE ADOPTED....,...,0,0,0,0,Other,0,0,UnknownMedium,15.203231,14.167982
4,4,Moderately Active,400.00000,1.0,64542.0,0.0,Poodle (Toy),White,0.0,Pierre is a petite little man with short legs ...,...,0,0,0,0,Other,0,0,AdultUnknown,21.707354,4.467046

In [144]:
result['SizeCurrent'].fillna(result['SizeCurrent_mean'], inplace=True)
result['SizePotential'].fillna(result['SizePotential_mean'], inplace=True)

In [145]:

result2['Age_at_Start'].fillna()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 152259 entries, 0 to 152258
Data columns (total 58 columns):
Unnamed: 0                 152259 non-null int64
ActivityLevel              152259 non-null object
AdoptionFee                152259 non-null float64
Altered                    152259 non-null float64
BiggestPictures            152259 non-null float64
BiggestVideos              152259 non-null float64
Breed                      152259 non-null object
Color                      152259 non-null object
Declawed                   152259 non-null float64
DescriptionPlain           152259 non-null object
GeneralAge                 152259 non-null object
GeneralSizePotential       152259 non-null object
Housetrained               152259 non-null object
IndoorOutdoor              152259 non-null object
LocationState              152259 non-null object
Microchipped               152259 non-null object
MixedBreed                 152259 non-null float64
NeedsFoster                152259 non-null float64
NewPeople                  152259 non-null object
NumPictures                152259 non-null float64
NumVideos                  152259 non-null float64
OKWithCats                 152259 non-null object
OKWithDogs                 152259 non-null object
OKWithKids                 152259 non-null object
OrgID                      152259 non-null float64
PrimaryBreed               152259 non-null object
SearchString               152259 non-null object
SecondaryBreed             152259 non-null object
Sex                        152259 non-null object
SizeCurrent                152259 non-null float64
SizePotential              152259 non-null float64
Specialneeds               152259 non-null float64
Uptodate                   152259 non-null float64
Start_Date                 152259 non-null object
End_Date                   152259 non-null object
Adopted                    152259 non-null int64
Censored                   152259 non-null int64
Time                       152259 non-null int64
Age_at_Start               128743 non-null float64
Has_url                    152259 non-null int64
In_Foster                  152259 non-null int64
Mostly_Black               152259 non-null int64
Region                     152259 non-null object
Search_String_Num_Terms    152259 non-null int64
Description_Length         152259 non-null int64
Desc_Latent_Topic          152259 non-null int64
Has_Video                  152259 non-null int64
Pitbull                    152259 non-null int64
Terrier                    152259 non-null int64
Hound                      152259 non-null int64
Herding                    152259 non-null int64
Working                    152259 non-null int64
Breed_Group                152259 non-null object
GoodShelter                152259 non-null int64
BadShelter                 152259 non-null int64
tempAgeSize                152259 non-null object
SizeCurrent_mean           152259 non-null float64
SizePotential_mean         152259 non-null float64
dtypes: float64(17), int64(18), object(23)
memory usage: 68.5+ MB

In [147]:
temp2 = r_df[['GeneralAge','Age_at_Start']].groupby(['GeneralAge']).agg(['mean'])
temp2.reset_index()

  GeneralAge Age_at_Start
                     mean
0      Adult     3.261336
1       Baby     0.003688
2     Senior     8.941824
3    Unknown     1.458259
4      Young     0.893219

In [150]:
temp2.columns = temp2.columns.get_level_values(0)

In [163]:
temp2 = temp2[['GeneralAge', 'Age_at_Start']]

In [164]:
temp2.columns = ['GeneralAge', 'Age_at_Start_mean']

In [165]:
result2 = pd.merge(result, temp2, how='left', on=['GeneralAge'])

In [166]:
result2.head()

,Unnamed: 0,ActivityLevel,AdoptionFee,Altered,BiggestPictures,BiggestVideos,Breed,Color,Declawed,DescriptionPlain,...,Hound,Herding,Working,Breed_Group,GoodShelter,BadShelter,tempAgeSize,SizeCurrent_mean,SizePotential_mean,Age_at_Start_mean
0,0,Unknown,265.08532,1.0,96769.0,0.0,Boxer,Unknown,0.0,IN NEED OF A FOSTER HOME UNTIL I CAN BE ADOPTE...,...,0,0,0,Other,0,0,AdultMedium,25.405390,10.479638,3.261336
1,1,Moderately Active,265.08532,1.0,95768.0,0.0,Labrador Retriever / Boxer / Mixed,Black,0.0,"Hi! My name is Bianca, and if you can believe ...",...,0,0,1,Working,0,0,AdultMedium,25.405390,10.479638,3.261336
2,2,Moderately Active,265.08532,1.0,98461.0,0.0,Labrador Retriever / Boxer / Mixed,Unknown,0.0,"I'm Mick, and I think I'm pretty darn handsome...",...,0,0,1,Working,0,0,YoungMedium,23.700970,14.040192,0.893219
3,3,Unknown,265.08532,1.0,84752.0,0.0,Boxer,Unknown,0.0,IN NEED OF FOSTER CARE UNTIL I CAN BE ADOPTED....,...,0,0,0,Other,0,0,UnknownMedium,15.203231,14.167982,1.458259
4,4,Moderately Active,400.00000,1.0,64542.0,0.0,Poodle (Toy),White,0.0,Pierre is a petite little man with short legs ...,...,0,0,0,Other,0,0,AdultUnknown,21.707354,4.467046,3.261336

In [167]:
result2['Age_at_Start'].fillna(result2['Age_at_Start_mean'],inplace=True)

In [169]:
result2.columns

Index([u'Unnamed: 0', u'ActivityLevel', u'AdoptionFee', u'Altered',
       u'BiggestPictures', u'BiggestVideos', u'Breed', u'Color', u'Declawed',
       u'DescriptionPlain', u'GeneralAge', u'GeneralSizePotential',
       u'Housetrained', u'IndoorOutdoor', u'LocationState', u'Microchipped',
       u'MixedBreed', u'NeedsFoster', u'NewPeople', u'NumPictures',
       u'NumVideos', u'OKWithCats', u'OKWithDogs', u'OKWithKids', u'OrgID',
       u'PrimaryBreed', u'SearchString', u'SecondaryBreed', u'Sex',
       u'SizeCurrent', u'SizePotential', u'Specialneeds', u'Uptodate',
       u'Start_Date', u'End_Date', u'Adopted', u'Censored', u'Time',
       u'Age_at_Start', u'Has_url', u'In_Foster', u'Mostly_Black', u'Region',
       u'Search_String_Num_Terms', u'Description_Length', u'Desc_Latent_Topic',
       u'Has_Video', u'Pitbull', u'Terrier', u'Hound', u'Herding', u'Working',
       u'Breed_Group', u'GoodShelter', u'BadShelter', u'tempAgeSize',
       u'SizeCurrent_mean', u'SizePotential_mean', u'Age_at_Start_mean'],
      dtype='object')

In [170]:
result2 = result2[[u'ActivityLevel', u'AdoptionFee', u'Altered',
       u'BiggestPictures', u'BiggestVideos', u'Breed', u'Color', u'Declawed',
       u'DescriptionPlain', u'GeneralAge', u'GeneralSizePotential',
       u'Housetrained', u'IndoorOutdoor', u'LocationState', u'Microchipped',
       u'MixedBreed', u'NeedsFoster', u'NewPeople', u'NumPictures',
       u'NumVideos', u'OKWithCats', u'OKWithDogs', u'OKWithKids', u'OrgID',
       u'PrimaryBreed', u'SearchString', u'SecondaryBreed', u'Sex',
       u'SizeCurrent', u'SizePotential', u'Specialneeds', u'Uptodate',
       u'Start_Date', u'End_Date', u'Adopted', u'Censored', u'Time',
       u'Age_at_Start', u'Has_url', u'In_Foster', u'Mostly_Black', u'Region',
       u'Search_String_Num_Terms', u'Description_Length', u'Desc_Latent_Topic',
       u'Has_Video', u'Pitbull', u'Terrier', u'Hound', u'Herding', u'Working',
       u'Breed_Group', u'GoodShelter', u'BadShelter']]

In [172]:
result2.to_csv('data/data.csv')

In [176]:
result2 = result2.drop('DescriptionPlain', axis=1)
result2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 152259 entries, 0 to 152258
Data columns (total 53 columns):
ActivityLevel              152259 non-null object
AdoptionFee                152259 non-null float64
Altered                    152259 non-null float64
BiggestPictures            152259 non-null float64
BiggestVideos              152259 non-null float64
Breed                      152259 non-null object
Color                      152259 non-null object
Declawed                   152259 non-null float64
GeneralAge                 152259 non-null object
GeneralSizePotential       152259 non-null object
Housetrained               152259 non-null object
IndoorOutdoor              152259 non-null object
LocationState              152259 non-null object
Microchipped               152259 non-null object
MixedBreed                 152259 non-null float64
NeedsFoster                152259 non-null float64
NewPeople                  152259 non-null object
NumPictures                152259 non-null float64
NumVideos                  152259 non-null float64
OKWithCats                 152259 non-null object
OKWithDogs                 152259 non-null object
OKWithKids                 152259 non-null object
OrgID                      152259 non-null float64
PrimaryBreed               152259 non-null object
SearchString               152259 non-null object
SecondaryBreed             152259 non-null object
Sex                        152259 non-null object
SizeCurrent                152259 non-null float64
SizePotential              152259 non-null float64
Specialneeds               152259 non-null float64
Uptodate                   152259 non-null float64
Start_Date                 152259 non-null object
End_Date                   152259 non-null object
Adopted                    152259 non-null int64
Censored                   152259 non-null int64
Time                       152259 non-null int64
Age_at_Start               152259 non-null float64
Has_url                    152259 non-null int64
In_Foster                  152259 non-null int64
Mostly_Black               152259 non-null int64
Region                     152259 non-null object
Search_String_Num_Terms    152259 non-null int64
Description_Length         152259 non-null int64
Desc_Latent_Topic          152259 non-null int64
Has_Video                  152259 non-null int64
Pitbull                    152259 non-null int64
Terrier                    152259 non-null int64
Hound                      152259 non-null int64
Herding                    152259 non-null int64
Working                    152259 non-null int64
Breed_Group                152259 non-null object
GoodShelter                152259 non-null int64
BadShelter                 152259 non-null int64
dtypes: float64(15), int64(17), object(21)
memory usage: 62.7+ MB

In [194]:
result2.to_csv('data/data_no_desc.csv')

In [195]:
missing = pd.read_csv('data/data_no_desc.csv')

In [193]:
result2['Microchipped'].unique()

array([0.0, 1.0, 'Unknown'], dtype=object)

In [191]:
result2['Microchipped'].replace('1.0', 1.0, inplace=True)

In [199]:
missing['Microchipped'].value_counts()

Unknown    78337
0.0        40838
1.0        24698
1.0         8386
Name: Microchipped, dtype: int64

In [201]:
result2['Description_Length'].max()

18857